services:
  superset:
    build:
      context: ..
      dockerfile: docker/Dockerfile.superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: secret_key
    depends_on:
      - postgres
    restart: unless-stopped
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname admin --lastname user --email admin@example.com --password admin || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "