FROM apache/superset

USER root

RUN /app/.venv/bin/python -m ensurepip && \
    /app/.venv/bin/python -m pip install --no-cache-dir --upgrade pip && \
    /app/.venv/bin/python -m pip install --no-cache-dir psycopg2-binary

USER superset